//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleParametro
    {
        public DetalleParametro()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public long Id_DetalleParametro { get; set; }
        public int DP_FK_Parametro { get; set; }
        public Nullable<long> DP_ValorNumero { get; set; }
        public string DP_ValorString { get; set; }
        public bool DP_Estado { get; set; }
    
        public virtual Parametro Parametro { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
