//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominioDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public long FK_DP_Rol { get; set; }
        public string Correo_Usuario { get; set; }
        public string NumeroCelular { get; set; }
        public decimal Cedula_Usuario { get; set; }
        public string Pass_Usuario { get; set; }
    }
}
